default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:480093451900:android:b42590c01b397ea2557bf9",
      firebase_cli_token: "1//091UegBL_2yQVCgYIARAAGAkSNwF-L9IrfGlYmZ3UtyvZkuKNkoeKCR7jziWQa7u0tQ_iIOMwZ2DBV5Vg1WAf7kOeW28V9B_79cc",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      groups: "testprod",
      release_notes: "First Fastlane Firebase Distribution"
  )
  end
end
